version: '3.5'

services:
  elastic:
    environment:
        # FIXME: Verify that other values of ELASTIC_MEM_SIZE are in fact accepted
        - "ES_JAVA_OPTS=-Xms${ELASTIC_MEM_SIZE:-256m} -Xmx${ELASTIC_MEM_SIZE:-256m}"
